-- Generated by Oracle SQL Developer Data Modeler 3.3.0.747
--   at:        2013-10-22 12:35:39 GMT+05:30
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE TABLE Actions
  (
    ActionID INT NOT NULL ,
    ActionName VARCHAR (50) NOT NULL ,
    Description VARCHAR (200) ,
    CreatedBy VARCHAR (100) NOT NULL ,
    CreatedDateTime DATE NOT NULL ,
    UpdatedBy VARCHAR (100) NOT NULL ,
    UpdatedDateTime DATE NOT NULL
  ) ;
ALTER TABLE Actions ADD CONSTRAINT Action_PK PRIMARY KEY
(
  ActionID
)
;

CREATE TABLE AgentDetails
  (
    AgentID INT NOT NULL ,
    AgentName VARCHAR (50) NOT NULL ,
    IP VARCHAR (20) ,
    Port INT ,
    MachineDetails VARCHAR (100) ,
    Instance VARCHAR (50) ,
    CreatedBy VARCHAR (100) NOT NULL ,
    CreatedDateTime DATE NOT NULL ,
    UpdatedBy VARCHAR (100) NOT NULL ,
    UpdatedDateTime DATE NOT NULL
  ) ;
CREATE INDEX AgectDetails_TestPlan_FK ON AgentDetails
  ( AgentID ASC
  ) ;
ALTER TABLE AgentDetails ADD CONSTRAINT AgectDetails_PK PRIMARY KEY
(
  AgentID
)
;

CREATE TABLE AppFeature
  (
    FeatureID INT NOT NULL ,
    FeatureName VARCHAR (50) NOT NULL ,
    Description VARCHAR (200) ,
    FunctionalID INT NOT NULL ,
    CreatedBy VARCHAR (100) NOT NULL ,
    CreatedDateTime DATE NOT NULL ,
    UpdatedBy VARCHAR (100) NOT NULL ,
    UpdatedDateTime DATE NOT NULL
  ) ;
ALTER TABLE AppFeature ADD CONSTRAINT Feature_PK PRIMARY KEY
(
  FeatureID
)
;

CREATE TABLE AppFunctionality
  (
    FunctionalID INT NOT NULL ,
    FunctionalName VARCHAR (50) NOT NULL ,
    Description VARCHAR (200) ,
    AppID INT NOT NULL ,
    CreatedBy VARCHAR (100) NOT NULL ,
    CreatedDateTime DATE NOT NULL ,
    UpdatedBy VARCHAR (100) NOT NULL ,
    UpdatedDateTime DATE NOT NULL
  ) ;
ALTER TABLE AppFunctionality ADD CONSTRAINT Functional_PK PRIMARY KEY
(
  FunctionalID
)
;

CREATE TABLE Application
  (
    AppID INT NOT NULL ,
    AppName VARCHAR (50) ,
    Description VARCHAR (200) ,
    CreatedBy VARCHAR (100) ,
    CreatedDateTime DATE ,
    UpdatedBy VARCHAR (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE Application ADD CONSTRAINT APPLICATION_PK PRIMARY KEY
(
  AppID
)
;

CREATE TABLE ConditionGroup
  (
    ConditionGroupID INT NOT NULL ,
    ConditionGroupName VARCHAR (50) NOT NULL ,
    Description VARCHAR (200) ,
    AppID INT NOT NULL ,
    CreatedBy VARCHAR (100) ,
    CreatedDateTime DATE ,
    UpdatedBy VARCHAR (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE ConditionGroup ADD CONSTRAINT ConditionGroup_PK PRIMARY KEY
(
  ConditionGroupID
)
;

CREATE TABLE Conditions
  (
    ConditionID INT NOT NULL ,
    ConditionName VARCHAR (50) ,
    Description VARCHAR (200) ,
    Expression VARCHAR (500) ,
    ConditionGroupID INT NOT NULL ,
    CreatedBy VARCHAR (100) ,
    CreatedDateTime DATE ,
    UpdatedBy VARCHAR (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE Conditions ADD CONSTRAINT Condition_PK PRIMARY KEY
(
  ConditionID
)
;

CREATE TABLE GenericData
  (
    ID INT NOT NULL ,
    KeyName VARCHAR (200) ,
    Value VARCHAR (200)
  ) ;
ALTER TABLE GenericData ADD CONSTRAINT GenericData_PK PRIMARY KEY
(
  ID
)
;

CREATE TABLE IdentifierType
  (
    IdentifierTypeID INT NOT NULL ,
    IndentifierTypeName VARCHAR (50) ,
    Description VARCHAR (200) ,
    AppID INT NOT NULL ,
    CreatedBy VARCHAR (100) ,
    CreatedDateTime DATE ,
    UpdatedBy VARCHAR (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE IdentifierType ADD CONSTRAINT IdentifierType_PK PRIMARY KEY
(
  IdentifierTypeID
)
;

CREATE TABLE LaneResults
  (
    TestRunID      INT NOT NULL ,
    ScheduleLaneID INT NOT NULL ,
    AgentID        INT NOT NULL ,
    BuildVersion VARCHAR (200) ,
    OS VARCHAR (200) ,
    Status VARCHAR (100) ,
    FailureDetails VARCHAR (200) ,
    CreatedBy VARCHAR (200) ,
    CreatedDateTime DATE ,
    UpdatedBy VARCHAR (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE LaneResults ADD CONSTRAINT DDTLaneResults_PK PRIMARY KEY
(
  TestRunID
)
;

CREATE TABLE ObjectGroup
  (
    ObjectGroupID INT NOT NULL ,
    ObjectGroupName VARCHAR (200) NOT NULL ,
    Description VARCHAR (200) ,
    AppID    INT NOT NULL ,
    ScreenID INT NOT NULL ,
    CreatedBy VARCHAR (100) NOT NULL ,
    CreatedDateTime DATE NOT NULL ,
    UpdatedBy VARCHAR (100) NOT NULL ,
    UpdatedDateTime DATE NOT NULL
  ) ;
ALTER TABLE ObjectGroup ADD CONSTRAINT ObjectGroup_PK PRIMARY KEY
(
  ObjectGroupID
)
;

CREATE TABLE ObjectType
  (
    ObjectTypeID INT NOT NULL ,
    ObjectTypeName VARCHAR (50) ,
    Description VARCHAR (200) ,
    AppID    INT NOT NULL ,
    ActionId INT NOT NULL ,
    CreatedBy VARCHAR (100) ,
    CreatedDateTime DATE ,
    UpdatedBy VARCHAR (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE ObjectType ADD CONSTRAINT ObjectType_PK PRIMARY KEY
(
  ObjectTypeID
)
;

CREATE TABLE Objects
  (
    ObjectID INT NOT NULL ,
    ObjectName VARCHAR (50) ,
    Description VARCHAR (200) ,
    ObjectGroupID    INT NOT NULL ,
    ObjectTypeID     INT NOT NULL ,
    IdentifierTypeID INT NOT NULL ,
    AppID            INT NOT NULL ,
    Identifier VARCHAR (4000) ,
    CreatedBy VARCHAR (100) ,
    CreatedDateTime DATE ,
    UpdatedBy VARCHAR (100) ,
    UpdatedDateTime DATE
  ) ;
CREATE INDEX Objects_APPLICATION_FK ON Objects
  ( ObjectID ASC
  ) ;
ALTER TABLE Objects ADD CONSTRAINT Objects_PK PRIMARY KEY
(
  ObjectID
)
;

CREATE TABLE Param
  (
    ParamID INT NOT NULL ,
    ParamName VARCHAR (200) ,
    Description VARCHAR (200) ,
    SortOrder    INT ,
    ParamGroupID INT NOT NULL ,
    ObjectID     INT NOT NULL ,
    CreatedBy VARCHAR (100) ,
    CreatedDateTime DATE ,
    UpdatedBy VARCHAR (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE Param ADD CONSTRAINT Parameter_PK PRIMARY KEY
(
  ParamID
)
;

CREATE TABLE ParamGroup
  (
    ParamGroupID INT NOT NULL ,
    ParamGroupName VARCHAR (200) ,
    Description VARCHAR (200) ,
    Tag VARCHAR (50) ,
    AppID          INT NOT NULL ,
    TestScenarioID INT NOT NULL ,
    TestCaseID     INT NOT NULL ,
    TestStepID     INT NOT NULL ,
    CreatedBy VARCHAR (100) ,
    CreatedDateTime DATE ,
    UpdatedBy VARCHAR (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE ParamGroup ADD CONSTRAINT ParamGroup_PK PRIMARY KEY
(
  ParamGroupID
)
;

CREATE TABLE Replacement_Strings
  (
    ID    INT NOT NULL ,
    AppID INT NOT NULL ,
    Level VARCHAR (50) ,
    Foreign_ID VARCHAR (50) ,
    Name VARCHAR (500) ,
    Value VARCHAR (500) ,
    ENCRYPTED INT
  ) ;
ALTER TABLE Replacement_Strings ADD CONSTRAINT Replacement_Strings_PK PRIMARY KEY
(
  ID
)
;

CREATE TABLE Runner
  (
    RunnerID INT NOT NULL ,
    RunnerName VARCHAR (50) NOT NULL ,
    Description VARCHAR (200) ,
    CreatedBy VARCHAR (100) NOT NULL ,
    CreatedDateTime DATE NOT NULL ,
    UpdatedBy VARCHAR (100) NOT NULL ,
    UpdatedDateTime DATE NOT NULL
  ) ;
ALTER TABLE Runner ADD CONSTRAINT Runner_PK PRIMARY KEY
(
  RunnerID
)
;

CREATE TABLE Scheduler
  (
    ScheduleID   INT NOT NULL ,
    TestPlanID   INT NOT NULL ,
    TestDataID   INT NOT NULL ,
    ScheduleTime DATE ,
    Status       VARCHAR(2) ,
    Frequency VARCHAR (200) ,
    Notifications VARCHAR(500),
    MultiLanes CHAR (1) NOT NULL ,
    CreatedBy VARCHAR (100) ,
    CreatedDateTime DATE ,
    UpdatedBy VARCHAR (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE Scheduler ADD CONSTRAINT Scheduler_PK PRIMARY KEY
(
  ScheduleID
)
;

CREATE TABLE SchedulerLaneDetails
  (
    ScheduleID     INT NOT NULL ,
    ScheduleLaneID INT NOT NULL ,
    LaneType VARCHAR (50) ,
    LaneUserName VARCHAR (50) ,
    RunnerType VARCHAR (100) ,
    Clones      INT ,
    Iterations  INT ,
    RampUpDelay INT ,
    Duration    INT
  ) ;
ALTER TABLE SchedulerLaneDetails ADD CONSTRAINT Lane_PK PRIMARY KEY
(
  ScheduleLaneID
)
;

CREATE TABLE SchedulerRunDetails
  (
    TestRunID  INT NOT NULL ,
    TestPlanID INT NOT NULL ,
    TestDataID INT NOT NULL ,
    ScheduleID INT NOT NULL ,
    Status     VARCHAR(2) ,
    RunTime    DATE ,
    CreatedBy VARCHAR (100) ,
    CreatedDateTime DATE ,
    UpdatedBy VARCHAR (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE SchedulerRunDetails ADD CONSTRAINT TestRunDetails_PK PRIMARY KEY
(
  TestRunID
)
;

CREATE TABLE Screen
  (
    ScreenID INT NOT NULL ,
    ScreenName VARCHAR (50) NOT NULL ,
    Description VARCHAR (200) ,
    AppID INT NOT NULL ,
    CreatedBy VARCHAR (100) NOT NULL ,
    CreatedDateTime DATE NOT NULL ,
    UpdatedBy VARCHAR (100) NOT NULL ,
    UpdatedDateTime DATE NOT NULL
  ) ;
ALTER TABLE Screen ADD CONSTRAINT Screen_PK PRIMARY KEY
(
  ScreenID
)
;

CREATE TABLE Task
  (
    TaskID INT NOT NULL ,
    LaneID INT NOT NULL ,
    TaskName VARCHAR (50) ,
    TestPlanXlsPath VARCHAR (200) ,
    DataSet VARCHAR (50) ,
    RepeatNo INT ,
    TagsToRun VARCHAR (200)
  ) ;
ALTER TABLE Task ADD CONSTRAINT Task_PK PRIMARY KEY
(
  TaskID
)
;

CREATE TABLE TaskResult
  (
    TaskResultID     INT NOT NULL ,
    TaskID           INT NOT NULL ,
    TaskPlanResultID INT ,
    RunResultID VARCHAR (500) ,
    ReportFilePath VARCHAR (500)
  ) ;
ALTER TABLE TaskResult ADD CONSTRAINT TaskResult_PK PRIMARY KEY
(
  TaskResultID
)
;

CREATE TABLE TestCase
  (
    TestCaseID INT NOT NULL ,
    ClassificationTag VARCHAR (500) ,
    CaseName VARCHAR (50) ,
    RunnerID INT NOT NULL ,
    Description VARCHAR (200) ,
    Active         CHAR (1) ,
    Positive       CHAR (1) ,
    SortOrder      INT ,
    TestScenarioId INT NOT NULL ,
    CreatedBy VARCHAR (100) ,
    CreatedDateTime DATE ,
    UpdatedBy VARCHAR (100) ,
    UpdatedDateTime DATE
  ) ;
CREATE INDEX TestCase_TestScenario_FK ON TestCase
  ( TestCaseID ASC
  ) ;
ALTER TABLE TestCase ADD CONSTRAINT TestCase_PK PRIMARY KEY
(
  TestCaseID
)
;

CREATE TABLE TestCaseResult
  (
    TestCaseResultID  INT NOT NULL ,
    TestCaseID        INT NOT NULL ,
    TestSuiteResultID INTEGER ,
    Result            VARCHAR(2) ,
    StartDateTime     DATE ,
    EndDateTime       DATE ,
    Comment         VARCHAR(2) ,
    EXCEPTION         VARCHAR(2) ,
    Request           VARCHAR(2) ,
    Response          VARCHAR(2)
  ) ;
ALTER TABLE TestCaseResult ADD CONSTRAINT TestCaseResult__IDX PRIMARY KEY
(
  TestCaseResultID
)
;

CREATE TABLE TestConditionData
  (
    TestConditionDataID INT NOT NULL ,
    TestDataID          INT NOT NULL ,
    ConditionGroupID    INT NOT NULL ,
    ConditionID         INT NOT NULL ,
    ConditionValue VARCHAR (200) ,
    CreatedBy VARCHAR (100) ,
    CreatedDateTime DATE ,
    UpdatedBy VARCHAR (100) ,
    UpdatedDateTime DATE
  ) ;
CREATE INDEX TestData_FK ON TestConditionData
  ( TestDataID ASC
  ) ;
CREATE INDEX TestCondition_FK ON TestConditionData
  ( ConditionID ASC
  ) ;
ALTER TABLE TestConditionData ADD CONSTRAINT TestCondData_PK PRIMARY KEY
(
  TestConditionDataID
)
;

CREATE TABLE TestData
  (
    TestDataID INT NOT NULL ,
    AppID      INT NOT NULL ,
    TestDataDescription VARCHAR (200) ,
    Status VARCHAR(2) ,
    CreatedBy VARCHAR (100) ,
    CreatedDateTime DATE ,
    UpdatedBy VARCHAR (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE TestData ADD CONSTRAINT TestData_PK PRIMARY KEY
(
  TestDataID
)
;

CREATE TABLE TestParamData
  (
    TestParamDataID INT NOT NULL ,
    ParamGroupID    INT NOT NULL ,
    TestDataID      INT NOT NULL ,
    ParamID         INT NOT NULL ,
    ParamValue VARCHAR (500) ,
    ValueBig BLOB ,
    CreatedBy VARCHAR (100) ,
    CreatedDateTime DATE ,
    UpdatedBy VARCHAR (100) ,
    UpdatedDateTime DATE
  ) ;
CREATE INDEX ParamGroup_FK ON TestParamData
  ( ParamGroupID ASC
  ) ;
CREATE INDEX TestData_FK ON TestParamData
  ( TestDataID ASC
  ) ;
ALTER TABLE TestParamData ADD CONSTRAINT TestParamData_PK PRIMARY KEY
(
  TestParamDataID
)
;

CREATE TABLE TestPlan
  (
    TestPlanID INT NOT NULL ,
    PlanName VARCHAR (50) ,
    Description VARCHAR (200) ,
    TestSuiteID          INT NOT NULL ,
    AppID                INT NOT NULL ,
    PreConditionGroupID  INT NOT NULL ,
    PostConditionGroupID INT NOT NULL ,
    CreatedBy VARCHAR (100) ,
    CreatedDateTime DATE ,
    UpdatedBy VARCHAR (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE TestPlan ADD CONSTRAINT TestPlan_PK PRIMARY KEY
(
  TestPlanID
)
;

CREATE TABLE TestPlanResult
  (
    TestPlanResultID INT NOT NULL ,
    TestPlanID       INT NOT NULL ,
    TestPlanRunName  VARCHAR(2) ,
    StartDateTime    DATE ,
    EndDateTime      DATE ,
    StatusSummary    VARCHAR(2)
  ) ;
ALTER TABLE TestPlanResult ADD CONSTRAINT TestPlanResult__IDX PRIMARY KEY
(
  TestPlanResultID
)
;

CREATE TABLE TestScenario
  (
    TestScenarioID INT NOT NULL ,
    TestScenarioName VARCHAR (500) ,
    Description VARCHAR (500) ,
    AppID       INT NOT NULL ,
    TestSuiteId INT NOT NULL ,
    SortOrder   INT ,
    CreatedBy VARCHAR (100) ,
    CreatedDateTime DATE ,
    UpdatedBy VARCHAR (100) ,
    UpdatedDateTime DATE
  ) ;
-- Error - Index TestScenario_APPLICATION_FK has no columns
ALTER TABLE TestScenario ADD CONSTRAINT TestScenario_PK PRIMARY KEY
(
  TestScenarioID
)
;

CREATE TABLE TestStep
  (
    TestStepID INT NOT NULL ,
    StepName VARCHAR (50) ,
    Description VARCHAR (200) ,
    TestStepType VARCHAR (100) ,
    ActionID             INT NOT NULL ,
    Active               CHAR (1) ,
    SortOrder            INT ,
    PreConditionGroupID  INT NOT NULL ,
    PostConditionGroupID INT NOT NULL ,
    InputParamGroupID    INT NOT NULL ,
    OutputParamGroupID   INT NOT NULL ,
    TestCaseID           INT NOT NULL ,
    RunnerID             INT NOT NULL ,
    ExpectedResult VARCHAR (50) ,
    CreatedBy VARCHAR (100) ,
    CreatedDateTime DATE ,
    UpdatedBy VARCHAR (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE TestStep ADD CONSTRAINT TestStep_PK PRIMARY KEY
(
  TestStepID
)
;

CREATE TABLE TestStepResult
  (
    TestStepResultID INT NOT NULL ,
    TestStepID       INT NOT NULL ,
    TestCaseResultID INT ,
    Result           VARCHAR(2) ,
    StartTime        DATE ,
    EndTime          DATE ,
    Comment        VARCHAR(2) ,
    EXCEPTION        VARCHAR(2) ,
    Request          VARCHAR(2) ,
    Response         VARCHAR(2)
  ) ;
ALTER TABLE TestStepResult ADD CONSTRAINT TestStepResult__IDX PRIMARY KEY
(
  TestStepResultID
)
;

CREATE TABLE TestSuite
  (
    TestSuiteID INT NOT NULL ,
    SuiteName VARCHAR (50) ,
    Description VARCHAR (200) ,
    AppID        INT NOT NULL ,
    FunctionalID INT NOT NULL ,
    FeatureID    INT NOT NULL ,
    SortOrder    CHAR (1) ,
    CreatedBy VARCHAR (100) ,
    CreatedDateTime DATE ,
    UpdatedBy VARCHAR (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE TestSuite ADD CONSTRAINT TestSuite_PK PRIMARY KEY
(
  TestSuiteID
)
;

CREATE TABLE TestSuiteResult
  (
    TestSuiteResultID INT NOT NULL ,
    TestSuiteID       INT NOT NULL ,
    TestPlanResultID  INT ,
    Result            VARCHAR(2) ,
    StartDateTime     DATE ,
    EndDateTime       DATE ,
    PercPassCount     INT ,
    PercFailCount     INT ,
    PercSkipCount     INT
  ) ;
ALTER TABLE TestSuiteResult ADD CONSTRAINT TestSuiteResult__IDX PRIMARY KEY
(
  TestSuiteResultID
)
;

ALTER TABLE TestPlan ADD CONSTRAINT AppID FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

ALTER TABLE ConditionGroup ADD CONSTRAINT ConditionGroup_APPLICATION_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

ALTER TABLE Conditions ADD CONSTRAINT Condition_ConditionGroup_FK FOREIGN KEY ( ConditionGroupID ) REFERENCES ConditionGroup ( ConditionGroupID ) ;

ALTER TABLE AppFeature ADD CONSTRAINT Feature_Functional_FK FOREIGN KEY ( FunctionalID ) REFERENCES AppFunctionality ( FunctionalID ) ON
DELETE CASCADE ;

ALTER TABLE AppFunctionality ADD CONSTRAINT Functional_APPLICATION_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ON
DELETE CASCADE ;

ALTER TABLE IdentifierType ADD CONSTRAINT IdentifierType_APPLICATION_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

ALTER TABLE ObjectGroup ADD CONSTRAINT ObjectGroup_APPLICATION_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

ALTER TABLE ObjectGroup ADD CONSTRAINT ObjectGroup_Screen_FK FOREIGN KEY ( ScreenID ) REFERENCES Screen ( ScreenID ) ;

ALTER TABLE ObjectType ADD CONSTRAINT ObjectType_APPLICATION_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

ALTER TABLE ObjectType ADD CONSTRAINT ObjectType_Actions_FK FOREIGN KEY ( ActionId ) REFERENCES Actions ( ActionID ) ;

ALTER TABLE Objects ADD CONSTRAINT Objects_Application_FK1 FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

ALTER TABLE Objects ADD CONSTRAINT Objects_IdentifierType_FK FOREIGN KEY ( IdentifierTypeID ) REFERENCES IdentifierType ( IdentifierTypeID ) ;

ALTER TABLE Objects ADD CONSTRAINT Objects_ObjectGroup_FK FOREIGN KEY ( ObjectGroupID ) REFERENCES ObjectGroup ( ObjectGroupID ) ON
DELETE CASCADE ;

ALTER TABLE Objects ADD CONSTRAINT Objects_ObjectType_FK FOREIGN KEY ( ObjectTypeID ) REFERENCES ObjectType ( ObjectTypeID ) ;

ALTER TABLE ParamGroup ADD CONSTRAINT ParamGroup_APPLICATION_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

ALTER TABLE ParamGroup ADD CONSTRAINT ParamGroup_TestCase_FK FOREIGN KEY ( TestCaseID ) REFERENCES TestCase ( TestCaseID ) ;

ALTER TABLE ParamGroup ADD CONSTRAINT ParamGroup_TestScenario_FK FOREIGN KEY ( TestScenarioID ) REFERENCES TestScenario ( TestScenarioID ) ;

ALTER TABLE ParamGroup ADD CONSTRAINT ParamGroup_TestStep_FK FOREIGN KEY ( TestStepID ) REFERENCES TestStep ( TestStepID ) ;

ALTER TABLE Param ADD CONSTRAINT Parameter_Objects_FK FOREIGN KEY ( ObjectID ) REFERENCES Objects ( ObjectID ) ;

ALTER TABLE Param ADD CONSTRAINT Parameter_ParamGroup_FK FOREIGN KEY ( ParamGroupID ) REFERENCES ParamGroup ( ParamGroupID ) ON
DELETE CASCADE ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE Replacement_Strings ADD CONSTRAINT Replacement_Strings_Application_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE SchedulerLaneDetails ADD CONSTRAINT SchedulerLaneDetails_Scheduler_FK FOREIGN KEY ( ScheduleID ) REFERENCES Scheduler ( ScheduleID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE SchedulerRunDetails ADD CONSTRAINT SchedulerRunDetails_Scheduler_FK FOREIGN KEY ( ScheduleID ) REFERENCES Scheduler ( ScheduleID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE SchedulerRunDetails ADD CONSTRAINT SchedulerRunDetails_TestData_FK FOREIGN KEY ( TestDataID ) REFERENCES TestData ( TestDataID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE SchedulerRunDetails ADD CONSTRAINT SchedulerRunDetails_TestPlan_FK FOREIGN KEY ( TestPlanID ) REFERENCES TestPlan ( TestPlanID ) ;

ALTER TABLE Scheduler ADD CONSTRAINT Scheduler_TestData_FK FOREIGN KEY ( TestDataID ) REFERENCES TestData ( TestDataID ) ;

ALTER TABLE Scheduler ADD CONSTRAINT Scheduler_TestPlan_FK FOREIGN KEY ( TestPlanID ) REFERENCES TestPlan ( TestPlanID ) ;

ALTER TABLE Screen ADD CONSTRAINT Screen_APPLICATION_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

ALTER TABLE Task ADD CONSTRAINT TABLE_32_Lane_FK FOREIGN KEY ( LaneID ) REFERENCES SchedulerLaneDetails ( ScheduleLaneID ) ;

ALTER TABLE TaskResult ADD CONSTRAINT TABLE_33_Task_FK FOREIGN KEY ( TaskID ) REFERENCES Task ( TaskID ) ;

ALTER TABLE LaneResults ADD CONSTRAINT DDTLaneResults_AgentDetails_FK FOREIGN KEY ( AgentID ) REFERENCES AgentDetails ( AgentID ) ;

ALTER TABLE LaneResults ADD CONSTRAINT DDTLaneResults_Lane_FK FOREIGN KEY ( ScheduleLaneID ) REFERENCES SchedulerLaneDetails ( ScheduleLaneID ) ;

ALTER TABLE TestCaseResult ADD CONSTRAINT TestCaseResult_TestCase_FK FOREIGN KEY ( TestCaseID ) REFERENCES TestCase ( TestCaseID ) ;

ALTER TABLE TestCase ADD CONSTRAINT TestCase_Runner_FK FOREIGN KEY ( RunnerID ) REFERENCES Runner ( RunnerID ) ;

ALTER TABLE TestCase ADD CONSTRAINT TestCase_TestScenario_FK1 FOREIGN KEY ( TestScenarioId ) REFERENCES TestScenario ( TestScenarioID ) ;

ALTER TABLE TestConditionData ADD CONSTRAINT TestCondData_ConditionGroup_FK FOREIGN KEY ( ConditionGroupID ) REFERENCES ConditionGroup ( ConditionGroupID ) ;

ALTER TABLE TestConditionData ADD CONSTRAINT TestCondData_Conditions_FK FOREIGN KEY ( ConditionID ) REFERENCES Conditions ( ConditionID ) ;

ALTER TABLE TestConditionData ADD CONSTRAINT TestCondData_TestData_FK FOREIGN KEY ( TestDataID ) REFERENCES TestData ( TestDataID ) ;

ALTER TABLE TestData ADD CONSTRAINT TestData_Application_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

ALTER TABLE TestParamData ADD CONSTRAINT TestParamData_ParamGroup_FK FOREIGN KEY ( ParamGroupID ) REFERENCES ParamGroup ( ParamGroupID ) ;

ALTER TABLE TestParamData ADD CONSTRAINT TestParamData_TestData_FK FOREIGN KEY ( TestDataID ) REFERENCES TestData ( TestDataID ) ;

ALTER TABLE TestPlanResult ADD CONSTRAINT TestPlanResult_TestPlan_FK FOREIGN KEY ( TestPlanID ) REFERENCES TestPlan ( TestPlanID ) ;

ALTER TABLE TestPlan ADD CONSTRAINT TestPlan_ConditionGroup_FK FOREIGN KEY ( PreConditionGroupID ) REFERENCES ConditionGroup ( ConditionGroupID ) ;

ALTER TABLE TestPlan ADD CONSTRAINT TestPlan_ConditionGroup_FKv2 FOREIGN KEY ( PostConditionGroupID ) REFERENCES ConditionGroup ( ConditionGroupID ) ;

ALTER TABLE TestPlan ADD CONSTRAINT TestPlan_TestSuite_FK FOREIGN KEY ( TestSuiteID ) REFERENCES TestSuite ( TestSuiteID ) ;

ALTER TABLE TestScenario ADD CONSTRAINT TestScenario_Application_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

ALTER TABLE TestScenario ADD CONSTRAINT TestScenario_TestSuite_FK FOREIGN KEY ( TestSuiteId ) REFERENCES TestSuite ( TestSuiteID ) ;

ALTER TABLE TestStepResult ADD CONSTRAINT TestStepResult_TestStep_FK FOREIGN KEY ( TestStepID ) REFERENCES TestStep ( TestStepID ) ;

ALTER TABLE TestStep ADD CONSTRAINT TestStep_Actions_FK FOREIGN KEY ( ActionID ) REFERENCES Actions ( ActionID ) ;

ALTER TABLE TestStep ADD CONSTRAINT TestStep_ConditionGroup_FK FOREIGN KEY ( PreConditionGroupID ) REFERENCES ConditionGroup ( ConditionGroupID ) ;

ALTER TABLE TestStep ADD CONSTRAINT TestStep_ConditionGroup_FKv1 FOREIGN KEY ( PostConditionGroupID ) REFERENCES ConditionGroup ( ConditionGroupID ) ;

ALTER TABLE TestStep ADD CONSTRAINT TestStep_ParamGroup_FK FOREIGN KEY ( InputParamGroupID ) REFERENCES ParamGroup ( ParamGroupID ) ;

ALTER TABLE TestStep ADD CONSTRAINT TestStep_ParamGroup_FKv1 FOREIGN KEY ( OutputParamGroupID ) REFERENCES ParamGroup ( ParamGroupID ) ;

ALTER TABLE TestStep ADD CONSTRAINT TestStep_Runner_FK FOREIGN KEY ( RunnerID ) REFERENCES Runner ( RunnerID ) ;

ALTER TABLE TestStep ADD CONSTRAINT TestStep_Runner_FKv1 FOREIGN KEY ( RunnerID ) REFERENCES Runner ( RunnerID ) ;

ALTER TABLE TestStep ADD CONSTRAINT TestStep_TestCase_FK FOREIGN KEY ( TestCaseID ) REFERENCES TestCase ( TestCaseID ) ;

ALTER TABLE TestStep ADD CONSTRAINT TestStep_TestCase_FKv1 FOREIGN KEY ( TestCaseID ) REFERENCES TestCase ( TestCaseID ) ;

ALTER TABLE TestStep ADD CONSTRAINT TestStep_TestStep_FK FOREIGN KEY ( TestStepID ) REFERENCES TestStep ( TestStepID ) ;

ALTER TABLE TestSuiteResult ADD CONSTRAINT TestSuiteResult_TestSuite_FK FOREIGN KEY ( TestSuiteID ) REFERENCES TestSuite ( TestSuiteID ) ;

ALTER TABLE TestSuite ADD CONSTRAINT TestSuite_APPLICATION_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ON
DELETE CASCADE ;

ALTER TABLE TestSuite ADD CONSTRAINT TestSuite_Application_FKv1 FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

ALTER TABLE TestSuite ADD CONSTRAINT TestSuite_Feature_FK FOREIGN KEY ( FeatureID ) REFERENCES AppFeature ( FeatureID ) ;

ALTER TABLE TestSuite ADD CONSTRAINT TestSuite_Functional_FK FOREIGN KEY ( FunctionalID ) REFERENCES AppFunctionality ( FunctionalID ) ;

ALTER TABLE GenericData ADD COLUMN AppID INT NOT NULL;

ALTER TABLE GenericData ADD CONSTRAINT AppID FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

ALTER TABLE AppFeature ADD COLUMN ScreenID INT NOT NULL;

ALTER TABLE AppFeature ADD CONSTRAINT ScreenID FOREIGN KEY ( ScreenID ) REFERENCES Screen ( ScreenID ) ;

ALTER TABLE TestCase ADD COLUMN ConditionGroupID INT NOT NULL;

ALTER TABLE TestCase ADD CONSTRAINT ConditionGroupID FOREIGN KEY ( ConditionGroupID ) REFERENCES ConditionGroup ( ConditionGroupID ) ;

ALTER TABLE ParamGroup ADD COLUMN ObjectGroupID INT NOT NULL;

ALTER TABLE ParamGroup ADD CONSTRAINT ObjectGroupID FOREIGN KEY ( ObjectGroupID ) REFERENCES ObjectGroup ( ObjectGroupID ) ;

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            35
-- CREATE INDEX                             7
-- ALTER TABLE                             98
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   7
-- WARNINGS                                 0
